spring:
  profiles:
    active: local
    group:
      local: local, common, secret
      blue: blue, common, secret
      green: green, common, secret

server:
  env: blue

---

spring:
  config:
    activate:
      on-profile: local

server:
  port: 8080
  serverAddress: localhost

serverName: local_server

---

spring:
  config:
    activate:
      on-profile: blue

server:
  port: ${server.port.blue}
  serverAddress: ${server.address.blue}

serverName: blue_server

---

spring:
  config:
    activate:
      on-profile: green

server:
  port: ${server.port.green}
  serverAddress: ${server.address.green}

serverName: green_server

---

spring:
  config:
    activate:
      on-profile: common

  application:
    name: apricot

  tomcat:
    uri-encoding: UTF-8

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true

  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

logging:
  level:
    org.hibernate.type.descriptor.sql: DEBUG
    org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver: ERROR

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: sandbox.apricot.member.vo, sandbox.apricot.interest.vo
  configuration:
    map-underscore-to-camel-case: true
#    cache-enabled: false
